updated backend url

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,13 +20,47 @@ jobs:
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
 
-    - name: Check Docker installation on EC2
+    - name: Identify Linux Distribution
       run: |
         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
-          echo 'Checking Docker installation...' &&
-          which docker || echo 'Docker not found' &&
-          docker --version || echo 'Docker version command failed' &&
-          sudo systemctl status docker || echo 'Docker service status check failed'
+          echo 'Linux Distribution:' &&
+          cat /etc/*release
+        "
+
+    - name: Install Docker
+      run: |
+        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
+          if [ -f /etc/os-release ]; then
+            . /etc/os-release
+            case $ID in
+              ubuntu|debian)
+                sudo apt-get update
+                sudo apt-get install -y docker.io
+                ;;
+              centos|rhel|fedora)
+                sudo yum install -y yum-utils
+                sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
+                sudo yum install -y docker-ce docker-ce-cli containerd.io
+                ;;
+              *)
+                echo 'Unsupported distribution'
+                exit 1
+                ;;
+            esac
+            sudo systemctl start docker
+            sudo systemctl enable docker
+            sudo usermod -aG docker $USER
+          else
+            echo 'Cannot identify the Linux distribution'
+            exit 1
+          fi
+        "
+
+    - name: Install Docker Compose
+      run: |
+        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
+          sudo curl -L 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose
+          sudo chmod +x /usr/local/bin/docker-compose
         "
 
     - name: Log in to Docker Hub
@@ -43,10 +77,6 @@ jobs:
     - name: Deploy to EC2
       run: |
         ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
-          sudo yum update -y &&
-          sudo amazon-linux-extras install docker -y &&
-          sudo service docker start &&
-          sudo usermod -a -G docker ec2-user &&
           echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin &&
           cd /home/${{ secrets.SSH_USER }}/bitcoin-explorer &&
           docker-compose down &&
