updated backend url

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,10 +21,16 @@ jobs:
       uses: webfactory/ssh-agent@v0.5.3
       with:
         ssh-private-key: ${{ secrets.SSH_KEY }}
+    - name: Setup Docker permissions on EC2
+      run: |
+        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
+          sudo usermod -aG docker ${{ secrets.SSH_USER }} &&
+          sudo systemctl restart docker
+        "
     - name: Log in to Docker Hub on EC2
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
-          echo '${{ secrets.DOCKER_PASSWORD}}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
+          echo '${{ secrets.DOCKER_PASSWORD }}' | sudo docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
         "
     - name: Create bitcoin-explorer directory
       run: |
@@ -44,7 +50,7 @@ jobs:
         ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
           set -e
           cd /home/${{ secrets.SSH_USER }}/bitcoin-explorer || (echo 'Failed to change directory' && exit 1)
-          docker-compose down || echo 'docker-compose down failed or not necessary'
-          docker-compose pull || (echo 'docker-compose pull failed' && exit 1)
-          docker-compose up -d --build || (echo 'docker-compose up failed' && exit 1)
+          sudo docker-compose down || echo 'docker-compose down failed or not necessary'
+          sudo docker-compose pull || (echo 'docker-compose pull failed' && exit 1)
+          sudo docker-compose up -d --build || (echo 'docker-compose up failed' && exit 1)
         "
